### ISSUE TITLE
tntnet 2.3rc1 - check fails with tntnet-test on fedora

### ISSUE THREAD

**Issue by martinkg** [maekitalo/cxxtools#10]
check fails by tntnet-test

ecppparser::testApplicationScope: ASSERTION at ecpptest.cpp:351 not equal: value1 (handler.result())= <start()onHtml(<foo>)onScope(application,default,,blah,)onHtml(</foo>)end()> value2 ("start()onHtml(<foo>)onScope(application,component,,blah,)onHtml(</foo>)end()")= <start()onHtml(<foo>)onScope(application,component,,blah,)onHtml(</foo>)end()> ecppparser::testThreadScope: ASSERTION at ecpptest.cpp:360 not equal: value1 (handler.result())= <start()onHtml(<foo>)onScope(thread,default,,blah,)onHtml(</foo>)end()> value2 ("start()onHtml(<foo>)onScope(thread,component,,blah,)onHtml(</foo>)end()")= <start()onHtml(<foo>)onScope(thread,component,,blah,)onHtml(</foo>)end()> ecppparser::testSessionScope: ASSERTION at ecpptest.cpp:369 not equal: value1 (handler.result())= <start()onHtml(<foo>)onScope(session,default,,blah,)onHtml(</foo>)end()> value2 ("start()onHtml(<foo>)onScope(session,component,,blah,)onHtml(</foo>)end()")= <start()onHtml(<foo>)onScope(session,component,,blah,)onHtml(</foo>)end()> ecppparser::testSecureSessionScope: ASSERTION at ecpptest.cpp:378 not equal: value1 (handler.result())= <start()onHtml(<foo>)onScope(secure_session,default,,blah,)onHtml(</foo>)end()> value2 ("start()onHtml(<foo>)onScope(secure_session,component,,blah,)onHtml(</foo>)end()")= <start()onHtml(<foo>)onScope(secure_session,component,,blah,)onHtml(</foo>)end()> ecppparser::testRequestScope: ASSERTION at ecpptest.cpp:387 not equal: value1 (handler.result())= <start()onHtml(<foo>)onScope(request,default,,blah,)onHtml(</foo>)end()> value2 ("start()onHtml(<foo>)onScope(request,component,,blah,)onHtml(</foo>)end()")= <start()onHtml(<foo>)onScope(request,component,,blah,)onHtml(</foo>)end()>

**Comment by maekitalo** [comment]
Part of those are wrong tests. But one is really a bug. I will fix that.

There is a new "default" scope. I did not fix the tests when I implemented it.

**Comment by martinkg** [comment]
i tried again compilation with your changes.
test/tntnet-test fails on arm platform see logs of the fedora build server: https://kojipkgs.fedoraproject.org//work/tasks/9563/10369563/build.log

**Comment by maekitalo** [comment]
I close this since you moved it to tntnet since it is a tntnet issue.
