### ISSUE TITLE
cxxtools build error

### ISSUE THREAD

**Issue by jm130794** [maekitalo/cxxtools#21]
Hello,

When we try to compile the latest version of cxxtools, we have errors :

make[1]: *** No rule to make target 'siconvert.cpp', needed by 'siconvert.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
mv -f .deps/netio.Tpo .deps/netio.Po
mv -f .deps/rpcasyncaddclient.Tpo .deps/rpcasyncaddclient.Po
mv -f .deps/rpcaddclient.Tpo .deps/rpcaddclient.Po
mv -f .deps/rpcechoclient.Tpo .deps/rpcechoclient.Po
mv -f .deps/rpcparallelecho.Tpo .deps/rpcparallelecho.Po
mv -f .deps/rpcserver.Tpo .deps/rpcserver.Po
mv -f .deps/saml2.Tpo .deps/saml2.Po
mv -f .deps/serialization.Tpo .deps/serialization.Po
make[1]: Leaving directory '/home/jm/cxxtools/demo'
Makefile:541: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by maekitalo** [comment]
obsolete
