### ISSUE TITLE
Final 3.0 release

### ISSUE THREAD

**Issue by aquette** [maekitalo/cxxtools#23]
Hello @maekitalo 
Do you have any idea or planned timeline for 3.0 release?
It seems that the 3.0rc2 is more than a year, and most linux distro (at least) still use a patched version of 2.2.1 which starts to be outdated (more than 4 years).
Please note that using milestone on GH (issue tab) can help providing visibility on the roadmap completion to achieve, and potentially get contributions to help you reaching that point.

thanks in advance,
Arno

**Comment by aggsol** [comment]
A 3.0 release would be great!

**Comment by maekitalo** [comment]
3.0 released

**Comment by aggsol** [comment]
Thank you for your great work!
