### ISSUE TITLE
configure fails on aarch64 in checking atomic type

### ISSUE THREAD

**Issue by bsg75** [maekitalo/cxxtools#25]
Hi,

 I am trying to compile cxxtools  on a Raspberry PI 3B running Arch Arm Linux with aarch64 architecture . Current git (7228f61) fails in the configure script at:
`checking atomic type... configure: error: check for atomictype failed`

Full config.log is attached.

My best guess is, that aarch64 needs to be added to `m4/asmtype.m4`, but I cannot do this be myself.

Any hints?

Cheers,
bsg75

[config.log](https://github.com/maekitalo/cxxtools/files/3481356/config.log)

**Comment by maekitalo** [comment]
This atomic stuff is a maintenance nightmare. Luckily C++11 has the functionality. So I decided to remove that and use std::atomic instead. So from now on C++11 is mandatory for cxxtools.

**Comment by bsg75** [comment]
Great, works :) thx!
