### ISSUE TITLE
cxxtools::Char::narrow looks wrong

### ISSUE THREAD

**Issue by jwakely** [maekitalo/cxxtools#28]
https://github.com/maekitalo/cxxtools/blob/b997a638b84252c97e6aa5a78ac55115d213f200/include/cxxtools/char.h#L381-L394

`std::char_traits<char>::eof()` is not a `char`, it's `std::char_traits<char>::int_type`, and its value is `EOF` which doesn't necessarily fit in a `char` (the C standard just says it's an `int` with a negative value).

`_value <= 0xff` is true for any negative value, which can happen because you use `int32_t` (i.e. a signed integral type) as your `Char::value_type`:

https://github.com/maekitalo/cxxtools/blob/b997a638b84252c97e6aa5a78ac55115d213f200/include/cxxtools/char.h#L68

This means that `Char(Char::value_type(-479)).narrow('?')` returns `'!'` and not `'?'` as expected.

Surely it should use `uint32_t`? The comments in the file repeatedly talk about unsigned 32-bit values, but everything is done with signed values.

https://github.com/maekitalo/cxxtools/blob/b997a638b84252c97e6aa5a78ac55115d213f200/include/cxxtools/char.h#L102-L107

Or are you implicitly assuming that only code points below U+10FFFF will get stored in `Char` and so there will be no negative values?

Also, the `char_traits<Char>::int_type` type is the same as `Char::value_type` which means that the `eof()` value is also a valid value of the `Char` type. It would probably make more sense to use `numeric_limits<uint64_t>::max()` for your eof value.

**Comment by maekitalo** [comment]
Yes, indeed. It was wrong. I added a unit test and fixed the bug. value_type is now uint32_t as planned and int_type is long. Actually I expect long to be longer as uint32_t.

**Comment by jwakely** [comment]
For ILP32 targets like 32-bit x86 `uint32_t` and `long` are both 32-bits.

**Comment by maekitalo** [comment]
You are right. I change int_type to int64_t

**Comment by maekitalo** [comment]
fixed with 89e5ad5c03bab261634ae7b7be757b9f75478803
