### ISSUE TITLE
cxxtools 2.3rc1 - test fails for armv7hl

### ISSUE THREAD

**Issue by martinkg** [maekitalo/cxxtools#9]
check fails in the test section for armv7hl

serializationinfo::testRangeCheck: ASSERTION at serializationinfo-test.cpp:494 exception of type std::range_error expected in siValue<double>(si) https://kojipkgs.fedoraproject.org//work/tasks/7169/10337169/build.log

**Comment by maekitalo** [comment]
It looks like double and long double are identical. The test expects, that long double has a larger maximum value than double. So it is a false positive.

I will just skip the test when the maximum of long double is not larger than the maximum of double.

**Comment by maekitalo** [comment]
The test is skipped now when double or float is not smaller than long double since overflow is not possible then.
